### ISSUE TITLE
Валидация форм настроек

### ISSUE THREAD

**Issue by qantus** [studio107/Core#9]
Сейчас настройки либо сохраняются и выводится сообщение что всё хорошо, либо не сохраняются и над настройками выводится сообщение что всё плохо и настройки не сохранены. Валидации непосредственно формы (под полями) сейчас нет.

**Comment by max107** [comment]
Closed by https://github.com/studio107/Admin/commit/e188484994eef1eb7c6241c32d2426c5731b70ae
